sudo: required
language: generic 

services: 
    - docker

before_install:
    - docker build -t skete/multi-reacttest -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true skete/multi-reacttest npm test
      
after_success:
    - docker build -t skete/multi-client ./client
    - docker build -t skete/multi-nginx ./nginx
    - docker build -t skete/multi-server ./server
    - docker build -t skete/multi-worker ./worker
    # log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take these images and push ut to dockerhub
    - docker push skete/multi-client:latest
    - docker push skete/multi-nginx:latest
    - docker push skete/multi-server:latest
    - docker push skete/multi-worker:latest


    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-876214055910
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY